steps = 300
image = "img.png"
flow = 0.005
species = [["N", [204, 255, 153], 0.1]]
cells = [["C", [204, 102, 255], 0.01], ["D",[224,31,31],0]] # name, color, inflow 
reactions = [
          {reactants = [[1,"C"], [1,"D"]], products = [], rate = [3,[2,2]]},
          {reactants = [[1,"C"], [1,"N"]], products = [[2,"C"]], rate = [1,[1,1]]},
	  {reactants = [[1,"D"], [1,"N"]], products = [[2,"D"]], rate = [1,[2,1]]}
	]	
