steps = 300
image = "img.png"
flow = 0.005
species = [ 
	{ name = "N", color = [204, 255, 153], inflow = 0.1 }
	]
cells = [
	{ name = "C", color = [204, 102, 255], inflow = 0.01, size = 1},
	{name = "D", color = [224, 31, 31], inflow = 0, size = 2}
	]
reactions = [
          {reactants = [[1,"C"], [1,"D"]], products = [], rate = [3,[2,2]]},
          {reactants = [[1,"C"], [1,"N"]], products = [[2,"C"]], rate = [1,[1,1]]},
	  {reactants = [[1,"D"], [1,"N"]], products = [[2,"D"]], rate = [1,[2,1]]}
	]	
