steps = 5000
image = "img.png"
flow = 0.001
species = [ 
	{ name = "N", color = [204, 255, 153], inflow = 0.001 }
	]
cells = [
	{ name = "prey", color = [204, 102, 255], inflow = 0},
	{name = "predator", color = [224, 31, 31], inflow = 0}
	]
reactions = [
          {reactants = [[1,"prey"], [1,"N"]], products = [[2, "prey"]], rate = [3,[1,1]]},
          {reactants = [[2,"prey"], [1,"predator"]], products = [[2,"predator"]], rate = [10,[2,1]]},
	  {reactants = [[1,"prey"]], products = [], rate = [0.8,[1]]},
	  {reactants = [[1,"predator"]], products = [], rate = [0.5,[1]]}
	]	
